# Generated by Django 5.2.17 on 2026-09-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image_url', models.URLField(max_length=500)),
                ('prep_time', models.IntegerField(help_text='Time in minutes')),
                ('tags', models.CharField(help_text='e.g., Tomato, Basil', max_length=200)),
            ],
        ),
    ]
