# Generated by Django 5.2.17 on 2026-09-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_recipe_description_recipe_ingredients_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='carbs',
            field=models.IntegerField(default=0, help_text='in grams'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='fats',
            field=models.IntegerField(default=0, help_text='in grams'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='protein',
            field=models.IntegerField(default=0, help_text='in grams'),
        ),
    ]
