# Generated by Django 5.2.17 on 2026-09-28 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_recipe_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='searchable_ingredients',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='playground.ingredient'),
        ),
    ]
