# Generated by Django 5.2.17 on 2026-09-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.IntegerField(default=1, help_text='Number of servings'),
        ),
    ]
